# Generated by Django 6.1.1 on 2026-09-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('COACH', 'Coach'), ('JOUEUR', 'Joueur'), ('DEV', 'DEV')], max_length=30, verbose_name='Rôle'),
        ),
    ]
