# Generated by Django 6.1.1 on 2026-09-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('COACH', 'Coach'), ('JOUEUR', 'Joueur'), ('ADMIN', 'Admin')], max_length=30, verbose_name='Rôle'),
        ),
    ]
